version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dimbus}
      POSTGRES_USER: ${POSTGRES_USER:-dimbus_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - internal

  shortener:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-dimbus_user}:${POSTGRES_PASSWORD:-changeme}@db:5432/${POSTGRES_DB:-dimbus}?sslmode=disable
    networks:
      - internal

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
      - public

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
  public:
    driver: bridge 