services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dimbus
      POSTGRES_USER: dimbus_user
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - internal

  shortener:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://dimbus_user:yourpassword@db:5432/dimbus?sslmode=disable
    ports:
      - "8080:8080"
    networks:
      - internal

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
      - public

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  internal:
  public: 